### Cadastrar um novo item de venda
POST https://localhost:5001/api/item/create
Content-Type: application/json

{
    "ProdutoId" : 1,
    "Quantidade" : 1,
    "Preco" : 3.5,
    "CarrinhoId" : "c1aec20e-3575-415d-93d9-940a52cca45b"
}

### Listar da Venda
GET https://localhost:5001/api/item/getbycartid/c1aec20e-3575-415d-93d9-940a52cca45b
