### Listar vendas
GET https://localhost:5001/api/venda/list


### Cadastrar uma nova Venda
POST https://localhost:5001/api/venda/create
Content-Type: application/json

{
        "Cliente": "Raphael Marangoni",
        "FormaPagamentoId": 1,
        "CarrinhoId": "c1aec20e-3575-415d-93d9-940a52cca45b"
}
